# Change these first
owner: s-codes14 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: portfolio
    url: https://s-codes14.github.io
  - name: smaller sites
    url: https://smaller-sites.netlify.app
  - name: 30sekify
    url: https://30sekify.netlify.app
  - name: cartoonized
    url: https://cartoonized.netlify.app/ 
  - name: animated
    url: https://s-codes14.github.io/animated 
  - name: Gradientful
    url: https://gradientful.netlify.app/
  - name: lordreklaw
    url: https://lordreklaw.netlify.app/
  - name: chess
    url: https://s-chess.netlify.app/ 
  - name: blog
    url: https://blog-s-codes14.netlify.app/
  - name: Rando prototype
    url: https://test-rando1.herokuapp.com
    
 
status-website: 
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#   cname: upptime
  baseUrl: /upptime
#   logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: S-codes14
  introTitle: "**Upptime**"
  introMessage: This is it
#   navbar:
#     - title: Status
#       href: /
#     - title: GitHub
#       href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
